___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [11]:
np.full((10), 5 * 1.0)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [41]:
np.array([i for i in range(10, 51)], np.float64)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

#### Create an array of all the even integers from 10 to 50

In [42]:
np.array([i for i in range(10, 51) if i % 2 != 0], np.float64)

array([11., 13., 15., 17., 19., 21., 23., 25., 27., 29., 31., 33., 35.,
       37., 39., 41., 43., 45., 47., 49.])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [40]:
np.array([i for i in range(9)], np.float64).reshape(3, 3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### Create a 3x3 identity matrix

In [26]:
np.diag([1.0, 1.0, 1.0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [39]:
import random
np.array([random.random()])

array([0.76261017])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [54]:
np.random.randn(25)

array([ 0.1328963 , -0.06878891, -0.8919384 ,  0.46365426,  1.41748387,
        0.44780974,  0.8605668 ,  0.44319683,  0.91113821, -0.96178198,
       -0.77791096, -0.4901134 , -0.45646694, -1.30077018, -0.25872856,
        0.06628574,  1.64347451, -0.32517934,  1.74463699,  0.11866052,
        0.67844939,  0.53212293,  0.84749787, -0.02071967,  0.41696905])

#### Create the following matrix:

In [53]:
np.random.randn(25)

array([ 2.06227341, -0.00906533, -0.897975  , -0.12141326, -2.40224496,
       -0.45129078,  1.07040931, -2.11229596, -2.18421843,  2.11202674,
        0.61253907,  0.81551072,  0.9319403 , -0.54741608,  2.08083538,
        0.47233143,  2.02079193, -0.63739321, -2.76455049, -1.20778956,
        0.6814063 ,  0.39935734,  0.57059527,  0.01659068,  0.07470295])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [52]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [62]:
np.array([12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25]).reshape(3, 4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [65]:
print(20)

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [70]:
np.array([2, 7, 12]).reshape(3, 1)

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [63]:
np.arange(21, 26)

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [64]:
np.arange(16, 26).reshape(2, 5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [72]:
print(sum(sum(mat)))

325


#### Get the standard deviation of the values in mat

In [74]:
print(np.std(mat))

7.211102550927978


#### Get the sum of all the columns in mat

In [73]:
np.array(sum(mat))

array([55, 60, 65, 70, 75])

# Great Job!